# 使用前请将此文件改名为config.yaml
appid: ""                          # qqbot的appid
secret: ""                         # qqbot的secret key
ip_addr: "ws://192.168.1.1"        # 本机公网或局域网地址
pic_token: ""                      # sm.ms的令牌，用于存储二维码图片
port: "5678"                       # dglab服务器的端口, 默认为5678